#!/usr/bin/env python3
"""Export palette and sprite data from the Python sim to C headers.

Run from the repo root:
    python firmware/scripts/export_assets.py

Generates:
    firmware/include/palette.h   — RGB565 colour constants
    firmware/include/sprites.h   — sprite pixel arrays in PROGMEM
"""

import os
import sys
import re

# Ensure the repo root is on the path so we can import rendering.*
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(0, REPO_ROOT)

from rendering import palette as P
from rendering import sprites as S


def rgb888_to_rgb565(r, g, b):
    """Convert 8-bit RGB to 16-bit RGB565."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


# ── palette.h ────────────────────────────────────────────────────────

# Colours to export: (C_NAME, python_attribute_name)
# We export every ALL_CAPS tuple in palette.py automatically.
def _palette_entries():
    """Yield (name, (r, g, b)) for every colour constant in palette.py."""
    for name in sorted(dir(P)):
        if name.startswith('_'):
            continue
        val = getattr(P, name)
        if isinstance(val, tuple) and len(val) == 3 and all(isinstance(c, int) for c in val):
            yield name, val


def generate_palette_h(path):
    lines = [
        '/* Auto-generated by export_assets.py — do not edit */',
        '#pragma once',
        '#include <stdint.h>',
        '',
        '// RGB565 palette colours (big-endian pixel order)',
    ]
    for name, (r, g, b) in _palette_entries():
        c565 = rgb888_to_rgb565(r, g, b)
        lines.append(f'#define PAL_{name:<20s} 0x{c565:04X}  '
                      f'// rgb({r}, {g}, {b})')

    lines.append('')

    with open(path, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'  wrote {path}  ({sum(1 for _ in _palette_entries())} colours)')


# ── sprites.h ────────────────────────────────────────────────────────

def _sprite_key_c():
    """Build a char→RGB565 mapping from S.SPRITE_KEY."""
    out = {}
    for ch, rgb in S.SPRITE_KEY.items():
        out[ch] = rgb888_to_rgb565(*rgb)
    return out


def _encode_sprite(sprite, key):
    """Return (width, height, [uint16_t ...]) for a sprite."""
    h = len(sprite)
    w = len(sprite[0]) if h else 0
    trans = rgb888_to_rgb565(*P.TRANSPARENT)
    pixels = []
    for row in sprite:
        for ch in row:
            pixels.append(key.get(ch, trans))
    return w, h, pixels


# Sprites to export: (C_NAME, python_attribute)
_SPRITES = [
    ('QUEEN',         S.QUEEN),
    ('WORKER_MINOR',  S.WORKER_MINOR),
    ('WORKER_NANITIC',S.WORKER_NANITIC),
    ('MAJOR',         S.MAJOR),
    ('EGG',           S.EGG),
    ('LARVA',         S.LARVA),
    ('PUPA',          S.PUPA),
]


def generate_sprites_h(path):
    key = _sprite_key_c()
    trans = rgb888_to_rgb565(*P.TRANSPARENT)

    lines = [
        '/* Auto-generated by export_assets.py — do not edit */',
        '#pragma once',
        '#include <stdint.h>',
        '#include <pgmspace.h>',
        '#include "palette.h"',
        '',
        f'#define SPRITE_TRANSPARENT 0x{trans:04X}',
        '',
    ]

    for cname, sprite in _SPRITES:
        w, h, pixels = _encode_sprite(sprite, key)
        lines.append(f'#define {cname}_W {w}')
        lines.append(f'#define {cname}_H {h}')
        lines.append(f'static const uint16_t {cname}[{w * h}] PROGMEM = {{')
        # Emit rows for readability
        for row_idx in range(h):
            row_pixels = pixels[row_idx * w : (row_idx + 1) * w]
            row_str = ', '.join(f'0x{p:04X}' for p in row_pixels)
            comma = ',' if row_idx < h - 1 else ''
            lines.append(f'    {row_str}{comma}')
        lines.append('};')
        lines.append('')

    with open(path, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'  wrote {path}  ({len(_SPRITES)} sprites)')


# ── main ─────────────────────────────────────────────────────────────

def main():
    include_dir = os.path.join(REPO_ROOT, 'firmware', 'include')
    os.makedirs(include_dir, exist_ok=True)

    print('Exporting assets …')
    generate_palette_h(os.path.join(include_dir, 'palette.h'))
    generate_sprites_h(os.path.join(include_dir, 'sprites.h'))
    print('Done.')


if __name__ == '__main__':
    main()
